export type ReportBranding = Readonly<{
  productName: string;
  logoText: string;
  generatedBy: string;
  gold: string;
  dark: string;
  muted: string;
  border: string;
  footer: string;
}>;

export const vorqaReportBranding: ReportBranding = Object.freeze({
  productName: "Vorqa AI",
  logoText: "VORQA",
  generatedBy: "Generated by VORA",
  gold: "#D6B36A",
  dark: "#111827",
  muted: "#64748B",
  border: "#E5E7EB",
  footer: "Vorqa AI - Construction Intelligence Report"
});

