import type { ExportReadyReport, ExportReadyReportSection } from "@/lib/analysis-hardening";
import { vorqaReportBranding, type ReportBranding } from "@/lib/report-branding";
import { getReportDirection, normalizeReportExportOptions, type ReportDirection, type ReportEvidenceReference, type ReportExportContext, type ReportExportOptions, type ReportLanguage } from "@/types/report-export";

export type ProfessionalReportMetadata = Readonly<{
  projectName?: string;
  projectId?: string;
  client?: string;
  organization?: string;
  analysisType?: string;
  analysisVersion?: number;
  healthScore?: string;
  confidenceScore?: number;
  generatedAt?: string;
  generatedBy?: string;
  workflowStage?: string;
}>;

export type ProfessionalReportSection = ExportReadyReportSection;

export type ProfessionalReportLabels = Readonly<Record<
  "project" | "projectId" | "client" | "organization" | "generated" | "generatedBy" | "analysisType" |
  "version" | "workflowStage" | "health" | "confidence" | "summary" | "findings" | "recommendations" |
  "risks" | "evidence" | "missingInformation" | "timeline" | "readiness" | "warnings" | "page" | "of",
  string
>>;

export type ProfessionalReport = Readonly<{
  title: string;
  language: ReportLanguage;
  direction: ReportDirection;
  labels: ProfessionalReportLabels;
  options: ReportExportOptions;
  metadata: ProfessionalReportMetadata;
  summary: readonly string[];
  findings: readonly string[];
  recommendations: readonly string[];
  risks: readonly string[];
  evidenceReferences: readonly ReportEvidenceReference[];
  missingInformation: readonly string[];
  timeline: NonNullable<ReportExportContext["timeline"]>;
  readiness?: ReportExportContext["readiness"];
  sections: readonly ProfessionalReportSection[];
  warnings: readonly string[];
  branding: ReportBranding;
}>;

const labels: Record<ReportLanguage, ProfessionalReportLabels> = {
  en: { project: "Project", projectId: "Project ID", client: "Client", organization: "Organization", generated: "Generated", generatedBy: "Generated by", analysisType: "Analysis type", version: "Version", workflowStage: "Workflow stage", health: "Health", confidence: "Confidence", summary: "Executive summary", findings: "Findings", recommendations: "Recommendations", risks: "Risks", evidence: "Evidence references", missingInformation: "Missing information", timeline: "Timeline", readiness: "Readiness", warnings: "Warnings", page: "Page", of: "of" },
  fr: { project: "Projet", projectId: "ID du projet", client: "Client", organization: "Organisation", generated: "Genere le", generatedBy: "Genere par", analysisType: "Type d'analyse", version: "Version", workflowStage: "Etape du flux", health: "Sante", confidence: "Confiance", summary: "Resume executif", findings: "Constats", recommendations: "Recommandations", risks: "Risques", evidence: "References des preuves", missingInformation: "Informations manquantes", timeline: "Chronologie", readiness: "Preparation", warnings: "Avertissements", page: "Page", of: "sur" },
  ar: { project: "المشروع", projectId: "معرف المشروع", client: "العميل", organization: "المؤسسة", generated: "تاريخ الإنشاء", generatedBy: "أُنشئ بواسطة", analysisType: "نوع التحليل", version: "الإصدار", workflowStage: "مرحلة سير العمل", health: "الصحة", confidence: "الثقة", summary: "الملخص التنفيذي", findings: "النتائج", recommendations: "التوصيات", risks: "المخاطر", evidence: "مراجع الأدلة", missingInformation: "المعلومات الناقصة", timeline: "الخط الزمني", readiness: "الجاهزية", warnings: "التحذيرات", page: "الصفحة", of: "من" }
};

function text(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function lines(values: readonly string[] | undefined) {
  return Object.freeze((values || []).map((line) => text(line)).filter((line): line is string => Boolean(line)));
}

function sectionText(report: ExportReadyReport, ids: readonly string[]) {
  return lines(report.sections
    .filter((section) => ids.some((id) => section.id.toLowerCase().includes(id) || section.title.toLowerCase().includes(id)))
    .flatMap((section) => section.content));
}

export function createProfessionalReportTemplate(input: {
  report: ExportReadyReport;
  metadata?: ProfessionalReportMetadata;
  context?: ReportExportContext;
  options?: Partial<ReportExportOptions>;
  branding?: ReportBranding;
}): ProfessionalReport {
  const report = input.report;
  const options = normalizeReportExportOptions(input.options);
  const metadata = input.metadata || {};
  const context = input.context || {};
  const confidence = typeof metadata.confidenceScore === "number" && Number.isFinite(metadata.confidenceScore)
    ? Math.max(0, Math.min(100, Math.round(metadata.confidenceScore)))
    : undefined;

  return Object.freeze({
    title: text(report.title) || "Vorqa AI",
    language: options.language,
    direction: getReportDirection(options.language),
    labels: labels[options.language],
    options,
    metadata: Object.freeze({
      ...(text(metadata.projectName || report.projectTitle) ? { projectName: text(metadata.projectName || report.projectTitle) } : {}),
      ...(text(metadata.projectId || report.projectId) ? { projectId: text(metadata.projectId || report.projectId) } : {}),
      ...(text(metadata.client) ? { client: text(metadata.client) } : {}),
      ...(text(metadata.organization) ? { organization: text(metadata.organization) } : {}),
      ...(text(metadata.analysisType || report.source.replace(/_/g, " ")) ? { analysisType: text(metadata.analysisType || report.source.replace(/_/g, " ")) } : {}),
      ...(typeof (metadata.analysisVersion ?? context.version) === "number" ? { analysisVersion: metadata.analysisVersion ?? context.version } : {}),
      ...(text(metadata.healthScore) ? { healthScore: text(metadata.healthScore) } : {}),
      ...(typeof confidence === "number" ? { confidenceScore: confidence } : {}),
      ...(text(metadata.generatedAt || report.generatedAt) ? { generatedAt: text(metadata.generatedAt || report.generatedAt) } : {}),
      ...(text(metadata.generatedBy || context.generatedBy) ? { generatedBy: text(metadata.generatedBy || context.generatedBy) } : {}),
      ...(text(metadata.workflowStage || context.workflowStage) ? { workflowStage: text(metadata.workflowStage || context.workflowStage) } : {})
    }),
    summary: sectionText(report, ["summary", "executive"]),
    findings: sectionText(report, ["finding", "clause", "overview", "detail"]),
    recommendations: options.includeRecommendations ? sectionText(report, ["recommend", "action", "next"]) : Object.freeze([]),
    risks: sectionText(report, ["risk", "warning"]),
    evidenceReferences: options.includeEvidenceReferences ? Object.freeze([...(context.evidenceReferences || [])]) : Object.freeze([]),
    missingInformation: lines(context.missingInformation),
    timeline: options.includeTimeline ? Object.freeze([...(context.timeline || [])]) : Object.freeze([]),
    readiness: options.includeReadiness ? context.readiness : undefined,
    sections: Object.freeze(report.sections.map((section) => Object.freeze({ ...section, content: lines(section.content) })).filter((section) => section.content.length > 0)),
    warnings: lines(report.warnings),
    branding: input.branding || vorqaReportBranding
  });
}

export function getReportMetadataRows(report: ProfessionalReport): readonly Readonly<[string, string]>[] {
  if (!report.options.includeProjectMetadata) return Object.freeze([]);
  const { metadata, labels: copy } = report;
  const rows: Array<readonly [string, string]> = [];
  const add = (label: string, value: unknown) => { if (value !== undefined && value !== "") rows.push(Object.freeze([label, String(value)])); };
  add(copy.project, metadata.projectName);
  add(copy.projectId, metadata.projectId);
  add(copy.client, metadata.client);
  add(copy.organization, metadata.organization);
  add(copy.analysisType, metadata.analysisType);
  add(copy.version, metadata.analysisVersion);
  add(copy.workflowStage, metadata.workflowStage);
  add(copy.health, metadata.healthScore);
  add(copy.confidence, typeof metadata.confidenceScore === "number" ? `${metadata.confidenceScore}%` : undefined);
  add(copy.generated, metadata.generatedAt);
  add(copy.generatedBy, metadata.generatedBy);
  return Object.freeze(rows);
}

export function renderReportPlainText(report: ProfessionalReport) {
  const section = (title: string, values: readonly string[]) => values.length ? ["", title, ...values] : [];
  return [
    ...(report.options.includeLogo ? [report.branding.logoText] : []),
    report.title,
    report.branding.generatedBy,
    ...getReportMetadataRows(report).map(([label, value]) => `${label}: ${value}`),
    ...section(report.labels.summary, report.summary),
    ...section(report.labels.findings, report.findings),
    ...section(report.labels.recommendations, report.recommendations.map((item) => `- ${item}`)),
    ...section(report.labels.risks, report.risks.map((item) => `- ${item}`)),
    ...report.sections.flatMap((item) => section(item.title, item.content)),
    ...section(report.labels.warnings, report.warnings.map((item) => `- ${item}`)),
    "",
    report.branding.footer
  ].join("\n");
}
