export const demoRfqs = [
  {
    id: "RFQ-1001",
    titleKey: "rfq.demo.luxuryVilla.title",
    descriptionKey: "rfq.demo.luxuryVilla.description",
    title: "Luxury Villa Casablanca execution package",
    project: "Luxury Villa Casablanca",
    status: "Open",
    budget: "MAD 8M - 12M",
    timeline: "6 months",
    category: "Contractors",
    dueDate: "2026-07-28",
    companies: ["Atlas Construction Group", "NorthBuild Engineering", "BetonPro Materials", "GeoConsult Africa"],
    description: "Requesting technical and commercial proposals for structural execution, material supply, engineering validation, and geotechnical advisory."
  },
  {
    id: "RFQ-1002",
    titleKey: "rfq.demo.rabatReview.title",
    descriptionKey: "rfq.demo.rabatReview.description",
    title: "Residential Complex Rabat permit and engineering review",
    project: "Residential Complex Rabat",
    status: "Draft",
    budget: "MAD 1.5M - 2.4M",
    timeline: "8 weeks",
    category: "Engineering Firms",
    dueDate: "2026-08-04",
    companies: ["NorthBuild Engineering", "UrbanForm Architects"],
    description: "Engineering and design review support before resubmitting permit documentation."
  },
  {
    id: "RFQ-1003",
    titleKey: "rfq.demo.tangierLogistics.title",
    descriptionKey: "rfq.demo.tangierLogistics.description",
    title: "Tangier warehouse steel and logistics support",
    project: "Industrial Warehouse Tangier",
    status: "Awarded",
    budget: "MAD 14M - 18M",
    timeline: "10 weeks",
    category: "Material Suppliers",
    dueDate: "Closed",
    companies: ["BetonPro Materials", "Maghreb Logistics", "CraneMax Equipment"],
    description: "Supplier and logistics package for steel delivery, crane access, and site material flow."
  },
  {
    id: "RFQ-1004",
    titleKey: "rfq.demo.marrakechAdvisory.title",
    descriptionKey: "rfq.demo.marrakechAdvisory.description",
    title: "Marrakech office tower foundation advisory",
    project: "Office Tower Marrakech",
    status: "Closed",
    budget: "MAD 700K - 1.1M",
    timeline: "4 weeks",
    category: "Consultants",
    dueDate: "Closed",
    companies: ["GeoConsult Africa", "NorthBuild Engineering"],
    description: "Closed request for foundation advisory and early risk assessment."
  }
];

export const demoQuotations = [
  {
    company: "Atlas Construction Group",
    logo: "ACG",
    price: "MAD 10.8M",
    totalPrice: 10800000,
    taxes: "MAD 1.08M",
    deliveryCost: "MAD 420K",
    paymentTerms: "20% advance / milestone payments",
    duration: "24 weeks",
    startAvailability: "2 weeks",
    warranty: "24 months",
    technicalCompliance: 94,
    commercialCompliance: 88,
    certifications: ["ISO 9001", "Site Safety Certified"],
    capacity: "High",
    responseTime: "Under 2 hours",
    reliability: "High",
    riskLevel: "Low",
    voraFit: 94,
    costBreakdown: { materials: 4200000, labor: 3100000, equipment: 1200000, logistics: 420000, taxes: 1080000, contingency: 800000 },
    technicalScores: { approach: 94, team: 92, experience: 96, delivery: 90, quality: 93, safety: 95, documentation: 91 },
    commercialScores: { price: 82, payment: 88, warranty: 92, schedule: 84, flexibility: 86, stability: 94 },
    rating: 4.9,
    badge: "Recommended",
    notes: "Best overall execution accountability with strong reporting and site management."
  },
  {
    company: "NorthBuild Engineering",
    logo: "NBE",
    price: "MAD 1.6M",
    totalPrice: 1600000,
    taxes: "MAD 160K",
    deliveryCost: "Included",
    paymentTerms: "30% advance / 70% delivery",
    duration: "6 weeks",
    startAvailability: "1 week",
    warranty: "12 months professional liability",
    technicalCompliance: 91,
    commercialCompliance: 90,
    certifications: ["Licensed Engineering Firm", "ISO 9001"],
    capacity: "Medium-high",
    responseTime: "Same business day",
    reliability: "Very high",
    riskLevel: "Lowest",
    voraFit: 91,
    costBreakdown: { materials: 120000, labor: 880000, equipment: 120000, logistics: 60000, taxes: 160000, contingency: 260000 },
    technicalScores: { approach: 92, team: 88, experience: 90, delivery: 89, quality: 92, safety: 88, documentation: 94 },
    commercialScores: { price: 90, payment: 84, warranty: 82, schedule: 92, flexibility: 88, stability: 90 },
    rating: 4.8,
    badge: "Lowest risk",
    notes: "Strong technical validation partner for structural and engineering review."
  },
  {
    company: "BetonPro Materials",
    logo: "BPM",
    price: "MAD 3.2M",
    totalPrice: 3200000,
    taxes: "MAD 320K",
    deliveryCost: "MAD 140K",
    paymentTerms: "15% advance / delivery batches",
    duration: "18 weeks",
    startAvailability: "10 days",
    warranty: "Material compliance warranty",
    technicalCompliance: 86,
    commercialCompliance: 92,
    certifications: ["Material Quality Certified", "ISO 9001"],
    capacity: "High supply capacity",
    responseTime: "Under 3 hours",
    reliability: "Strong",
    riskLevel: "Medium",
    voraFit: 86,
    costBreakdown: { materials: 2250000, labor: 180000, equipment: 120000, logistics: 140000, taxes: 320000, contingency: 190000 },
    technicalScores: { approach: 84, team: 82, experience: 88, delivery: 86, quality: 90, safety: 82, documentation: 89 },
    commercialScores: { price: 95, payment: 90, warranty: 84, schedule: 86, flexibility: 88, stability: 86 },
    rating: 4.6,
    badge: "Best value",
    notes: "Competitive material supply proposal with verified quality documentation."
  },
  {
    company: "GeoConsult Africa",
    logo: "GCA",
    price: "MAD 820K",
    totalPrice: 820000,
    taxes: "MAD 82K",
    deliveryCost: "Included",
    paymentTerms: "40% advance / 60% report delivery",
    duration: "4 weeks",
    startAvailability: "Immediate",
    warranty: "Professional advisory liability",
    technicalCompliance: 90,
    commercialCompliance: 86,
    certifications: ["Geotechnical Consultancy License", "Lab Testing Certified"],
    capacity: "Specialist advisory capacity",
    responseTime: "Under 1 business day",
    reliability: "High",
    riskLevel: "Low",
    voraFit: 90,
    costBreakdown: { materials: 60000, labor: 430000, equipment: 90000, logistics: 45000, taxes: 82000, contingency: 113000 },
    technicalScores: { approach: 90, team: 86, experience: 91, delivery: 94, quality: 88, safety: 86, documentation: 92 },
    commercialScores: { price: 88, payment: 78, warranty: 82, schedule: 96, flexibility: 84, stability: 87 },
    rating: 4.8,
    badge: "Fastest advisory",
    notes: "Fast geotechnical advisory and foundation risk summary."
  }
];

export const rfqWizardSteps = [
  "Project Information",
  "Requested Services",
  "Budget Range",
  "Timeline",
  "Select Companies",
  "Review & Submit"
];

export const awardSteps = [
  "Select winning quotation",
  "Confirm scope and final price",
  "Add award notes",
  "Review decision",
  "Award confirmation"
];
